server:
  port: 9001
## spring security配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${db.url}?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: ${db.dname}
    password: ${db.dpwd}

  security:
    user:
      name: admin
      password: 123

logging:
  level:
    org:
      springframework:
        security: info